from fastapi import APIRouter

from app.api.v1.endpoints import (
    analytics,
    assignments,
    auth,
    courses,
    evaluations,
    health,
    submissions,
    uploads,
    users,
)

api_router = APIRouter()

api_router.include_router(
    health.router,
    tags=["Health"],
)
api_router.include_router(
    auth.router,
    prefix="/auth",
    tags=["Authentication"],
)
api_router.include_router(
    users.router,
    prefix="/users",
    tags=["Users"],
)
api_router.include_router(
    courses.router,
    prefix="/courses",
    tags=["Courses"],
)
api_router.include_router(
    courses.enrollments_router,
    prefix="/enrollments",
    tags=["Enrollments"],
)
api_router.include_router(
    assignments.router,
    prefix="/assignments",
    tags=["Assignments"],
)
api_router.include_router(
    assignments.rubrics_router,
    prefix="/rubrics",
    tags=["Rubrics"],
)
api_router.include_router(
    submissions.router,
    prefix="/submissions",
    tags=["Submissions"],
)
api_router.include_router(
    uploads.router,
    prefix="/uploads",
    tags=["Uploads"],
)
api_router.include_router(
    evaluations.router,
    prefix="/evaluations",
    tags=["Evaluations"],
)
api_router.include_router(
    analytics.router,
    prefix="/analytics",
    tags=["Analytics"],
)
